class Constants {
  double deviceWidth = 888.0;
  double deviceHeight = 406.6666666666667;
  String ngrokurl = 'https://b27b-35-199-13-144.ngrok-free.app';
  String base_url = 'http://13.200.249.129:8080';
  List<String> TTSLocaleIDS = [
    'hr-HR',
    'ko-KR',
    'mr-IN',
    'ru-RU',
    'zh-TW',
    'hu-HU',
    'sw-KE',
    'th-TH',
    'ur-PK',
    'nb-NO',
    'da-DK',
    'tr-TR',
    'et-EE',
    'pt-PT',
    'vi-VN',
    'en-US',
    'sq-AL',
    'sv-SE',
    'ar',
    'su-ID',
    'bn-BD',
    'bs-BA',
    'gu-IN',
    'kn-IN',
    'el-GR',
    'hi-IN',
    'he-IL',
    'fi-FI',
    'bn-IN',
    'km-KH',
    'fr-FR',
    'uk-UA',
    'pa-IN',
    'en-AU',
    'nl-NL',
    'fr-CA',
    'lv-LV',
    'sr',
    'pt-BR',
    'de-DE',
    'ml-IN',
    'si-LK',
    'cs-CZ',
    'is-IS',
    'pl-PL',
    'ca-ES',
    'sk-SK',
    'it-IT',
    'fil-PH',
    'lt-LT',
    'ne-NP',
    'ms-MY',
    'en-NG',
    'nl-BE',
    'zh-CN',
    'es-ES',
    'ja-JP',
    'ta-IN',
    'bg-BG',
    'cy-GB',
    'yue-HK',
    'es-US',
    'en-IN',
    'jv-ID',
    'id-ID',
    'te-IN',
    'ro-RO',
    'en-GB'
  ];
  List<String> TTSDisplay = [
    'Croatian',
    'Korean',
    'Marathi',
    'Russian',
    'Chinese (Traditional, Taiwan)',
    'Hungarian',
    'Swahili',
    'Thai',
    'Urdu',
    'Norwegian Bokmål',
    'Danish',
    'Turkish',
    'Estonian',
    'Portuguese (Portugal)',
    'Vietnamese',
    'English (United States)',
    'Albanian',
    'Swedish',
    'Arabic',
    'Sundanese',
    'Bengali (Bangladesh)',
    'Bosnian',
    'Gujarati',
    'Kannada',
    'Greek',
    'Hindi',
    'Hebrew',
    'Finnish',
    'Bengali (India)',
    'Khmer',
    'French (France)',
    'Ukrainian',
    'Punjabi (India)',
    'English (Australia)',
    'Dutch',
    'French (Canada)',
    'Latvian',
    'Serbian',
    'Portuguese (Brazil)',
    'German',
    'Malayalam',
    'Sinhala',
    'Czech',
    'Icelandic',
    'Polish',
    'Catalan',
    'Slovak',
    'Italian',
    'Filipino (Philippines)',
    'Lithuanian',
    'Nepali',
    'Malay (Malaysia)',
    'English (Nigeria)',
    'Dutch (Belgium)',
    'Chinese (Simplified, China)',
    'Spanish (Spain)',
    'Japanese',
    'Tamil (India)',
    'Bulgarian',
    'Welsh',
    'Cantonese (Hong Kong)',
    'Spanish (United States)',
    'English (India)',
    'Javanese',
    'Indonesian',
    'Telugu (India)',
    'Romanian',
    'English (United Kingdom)'
  ];
}
